services:
  postgres:
    image: postgres
    container_name: postgresql
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: exampledb
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: unless-stopped
    network_mode: bridge
