services:
  typecho:
    image: joyqi/typecho:nightly-php7.4-apache
    # container_name: typecho
    environment:
      - TYPECHO_SITE_URL=https://your-domain.com
    ports:
      - 0:80
    volumes:
      - ./app:/app
      - ./app/usr:/app/usr
    restart: unless-stopped
    network_mode: bridge
