services:
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin:latest
    ports:
      - 0:80
    deploy:
      resources:
        limits:
          memory: 500M
    restart: unless-stopped
    network_mode: bridge
