FROM java

RUN java -jar jenkins.war --httpPort=8889 --prefix=/jenkins

# docker run -d -p 8088:8080 -p 50000:50000 -v /usr/local/jenkins:/var/jenkins_home --name hello-jenkins jenkins/jenkins:latest
# 