services:
  teemii-frontend:
    image: dokkaner/teemii-frontend:latest
    container_name: teemii-web
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "8034:80"
    environment:
      - VITE_APP_TITLE=Teemii
      - VITE_APP_PORT=80
  teemii-backend:
    image: dokkaner/teemii-backend:latest
    container_name: teemii-server
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./data:/data
    environment:
      - EXPRESS_PORT=3000
      - SOCKET_IO_PORT=1555
