services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: your_password
    volumes:
      - './data:/var/lib/mysql'
      - './config:/etc/mysql/conf.d'
    restart: unless-stopped
    network_mode: bridge
