version: "3.7"

services:
    chromium:
        image: lscr.io/linuxserver/chromium:latest
        container_name: chromium
        security_opt:
            - seccomp:unconfined
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Shanghai
            - CHROME_CLI=https://www.baidu.com
        volumes:
            - /path/to/config:/config
        ports:
            - 3000:3000
            - 3001:3001
        shm_size: "1gb"
        restart: unless-stopped
