services:
  backend:
    image: 4gray/iptvnator-backend:latest
    container_name: iptvnator-backend
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "4334:3000"
    environment:
      - CLIENT_URL=http://frontend:4333 # 与前端服务地址匹配

  frontend:
    image: 4gray/iptvnator:latest
    container_name: iptvnator-web
    restart: unless-stopped
    network_mode: bridge
    ports:
      - "4333:80"
    environment:
      - BACKEND_URL=http://backend:4334 # 与后端服务地址匹配
