services:
  sun-panel:
    image: 'hslr/sun-panel:latest'
    container_name: sun-panel
    volumes:
      - ./conf:/app/conf
      - ./uploads:/app/uploads
      - ./database:/app/database
    ports:
      - 3002:3002
    restart: unless-stopped
