name: 🚀 Deploy Typecho on push with FTP

on:
  push:
    branches:
      - master
    paths:
      - "php/typecho-1.1.17.10.30/**"

jobs:
  deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      # - name: Install composer dependencies
      #   run: cd ./composer/skycaiji-v2.9.4 && composer install

      # - name: Install node dependencies
      #   run: npm install

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          # ftp server
          server: ftpupload.net
          # ftp username
          username: b7_34048879
          # ftp password
          password: ${{ secrets.ftp_password }}
          # Upload entire repository
          local-dir: "./php/typecho-1.1.17.10.30/"
          # Path to upload to on the server. Must end with trailing slash /
          server-dir: /typecho.22web.org/htdocs/
